version: '2'
services:
    schoolwebproject-app:
        image: schoolwebproject
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://schoolwebproject-postgresql:5432/SchoolWebProject
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    schoolwebproject-postgresql:
        extends:
            file: postgresql.yml
            service: schoolwebproject-postgresql
